web/Areas/Admin/Controllers/HumanResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.HRBL;
using BLL.LanguageBL;
using DAL.Entities;
using web.Areas.Admin.Filters;
using System.IO;
using web.Areas.Admin.Helpers;
using System.Web.Script.Serialization;

namespace web.Areas.Admin.Controllers
{
      [AuthenticateUser]
    public class HumanResourceController : Controller
    {
        //
        // GET: /Admin/HumanResource/

        public ActionResult Index()
        {
            string lang = FillLanguagesList();

            var vision_info = HumanResourceManager.GetHRByLanguage(lang);
            return View(vision_info);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Index(HumanResource record)
        {
            string lang = FillLanguagesList();
            record.Language = lang;

            ViewBag.ProcessMessage = HumanResourceManager.EditHumanResource(record);


            return View();
        }

        public ActionResult HumanResourcePositions()
        {
            string sellang = FillLanguagesList();

            var referncelist = HumanResourceManager.GetHumanResourcePositionList(sellang);
            return View(referncelist);
        }

        public ActionResult AddHumanResourcePosition()
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;

            return View();
        }

        [HttpPost]
        public ActionResult AddHumanResourcePosition(HumanResourcePosition newmodel)
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if (ModelState.IsValid)
            {
                newmodel.SortOrder = 9999;
                newmodel.TimeCreated = DateTime.Now;
                ViewBag.ProcessMessage = HumanResourceManager.AddHumanResourcePosition(newmodel);
                ModelState.Clear();
                // Response.Redirect("/yonetim/haberduzenle/" + newsmodel.NewsId);
                return View();
            }
            else
                return View();
        }

        public ActionResult EditHumanResourcePosition()
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if (RouteData.Values["id"] != null)
            {
                int nid = 0;
                bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                if (isnumber)
                {
                    HumanResourcePosition editHumanResourcePosition = HumanResourceManager.GetHumanResourcePositionById(nid);
                    return View(editHumanResourcePosition);
                }
                else
                    return View();
            }
            else
                return View();
            return View();
        }

        [HttpPost]
        public ActionResult EditHumanResourcePosition(HumanResourcePosition HumanResourcePositionmodel)
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;

            if (ModelState.IsValid)
            {
                
                if (RouteData.Values["id"] != null)
                {
                    int nid = 0;
                    bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                    if (isnumber)
                    {
                        HumanResourcePositionmodel.HumanResourcePositionId = nid;
                        ViewBag.ProcessMessage = HumanResourceManager.EditHumanResourcePosition(HumanResourcePositionmodel);
                        return View(HumanResourcePositionmodel);
                    }
                    else
                    {
                        ViewBag.ProcessMessage = false;
                        return View(HumanResourcePositionmodel);
                    }
                }
                else return View();
            }
            else
                return View();

            return View();
        }


        public JsonResult HumanResourcePositionEditStatus(int id)
        {
            string NowState;
            bool isupdate = HumanResourceManager.UpdateStatus(id);
            return Json(isupdate);
        }


        public JsonResult DeleteHumanResourcePosition(int id)
        {
            bool isdelete = HumanResourceManager.Delete(id);
            //if (isdelete)
            return Json(isdelete);
            //  else return false;
        }

        public JsonResult SortRecords(string list)
        {
            JsonList psl = (new JavaScriptSerializer()).Deserialize<JsonList>(list);
            string[] idsList = psl.list;
            bool issorted = HumanResourceManager.SortRecords(idsList);
            return Json(issorted);


        }

        public class JsonList
        {
            public string[] list { get; set; }
        }
       

        string FillLanguagesList()
        {
            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language", lang);
            ViewBag.LanguageList = list;
            return lang;
        }
    }
}

web/Areas/Admin/Views/HumanResource/AddHumanResourcePosition.cshtml
@model DAL.Entities.HumanResourcePosition
@{
    ViewBag.Title = "AddHumanResourcePosition";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("hr_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>İNSAN KAYNAKLARI BİLGİLERİ</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using(Html.BeginForm("AddHumanResourcePosition", "HumanResource", FormMethod.Post, new { enctype = "multipart/form-data"}))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Pozisyon Ekle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.HumanResourcePositionName)
            @Html.TextBoxFor(m=>m.HumanResourcePositionName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.HumanResourcePositionName)
        </p>
        
        <p>
            @Html.LabelFor(m=>m.Workdef)
            @Html.TextAreaFor(m=>m.Workdef, new { @class="textwidth50", @rows="5"})
            @Html.ValidationMessageFor(m=>m.Workdef)
        </p>
        <p>
            @Html.LabelFor(m=>m.Content)
            @Html.TextAreaFor(m=>m.Content, new { @class="textwidth50", @rows="5"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/HumanResourcePosition/addHumanResourcePosition.js"></script>
}

web/Areas/Admin/Views/HumanResource/AddPosition.cshtml
@model DAL.Entities.HumanResourcePosition
@{
    ViewBag.Title = "AddHumanResourcePosition";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("hr_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>İNSAN KAYNAKLARI BİLGİLERİ</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using(Html.BeginForm("AddHumanResourcePosition", "HumanResourcePosition", FormMethod.Post, new { enctype = "multipart/form-data"}))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>İNSAN KAYNAKLARI Ekle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.HumanResourcePositionName)
            @Html.TextBoxFor(m=>m.HumanResourcePositionName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.HumanResourcePositionName)
        </p>
        
        <p>
            @Html.LabelFor(m=>m.Content)
            @Html.TextAreaFor(m=>m.Content, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/HumanResourcePosition/addHumanResourcePosition.js"></script>
}

web/Areas/Admin/Views/HumanResource/EditHumanResourcePosition.cshtml
@model DAL.Entities.HumanResourcePosition
@{
    ViewBag.Title = "EditHumanResourcePosition";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("hr_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>POZiSYON BiLGiLERi</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using (Html.BeginForm("EditHumanResourcePosition", "HumanResource", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Pozisyon Duzenle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.HumanResourcePositionName)
            @Html.TextBoxFor(m=>m.HumanResourcePositionName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.HumanResourcePositionName)
        </p>
         <p>
            @Html.LabelFor(m=>m.Workdef)
            @Html.TextAreaFor(m=>m.Workdef, new { @class="textwidth50", @rows="5"})
            @Html.ValidationMessageFor(m=>m.Workdef)
        </p>
        <p>
            @Html.LabelFor(m=>m.Content)
            @Html.TextAreaFor(m=>m.Content, new { @class="textwidth50", @rows="5"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/HumanResourcePosition/addHumanResourcePosition.js"></script>
}

web/Areas/Admin/Views/HumanResource/EditPosition.cshtml
@model DAL.Entities.HumanResourcePosition
@{
    ViewBag.Title = "EditHumanResourcePosition";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("hr_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>POZİSYON BILGILERI</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using (Html.BeginForm("EditHumanResourcePosition", "HumanResource", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Pozisyon Duzenle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.HumanResourcePositionName)
            @Html.TextBoxFor(m=>m.HumanResourcePositionName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.HumanResourcePositionName)
        </p>
        
        <p>
            @Html.LabelFor(m=>m.Content)
            @Html.TextAreaFor(m=>m.Content, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/HumanResourcePosition/addHumanResourcePosition.js"></script>
}

web/Areas/Admin/Views/HumanResource/HumanResourcePositions.cshtml
@model IEnumerable<DAL.Entities.HumanResourcePosition>
@{
    ViewBag.Title = "Positions";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("hr_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>POZİSYON BİLGİLERİ</h2>
    </div>  
    <section class="grid_12 form">
    <div class="box-header" >
        <h1>Pozisyon Listesi&nbsp;&nbsp;|&nbsp;&nbsp;
             @Html.DropDownList("LanguageList")
        </h1>

    </div>
    <table id="tblcategory" class="table no-border tablesorter">
        <thead>
            <tr>
                 <th class="width5">Sırala</th>
                <th class="width50">Pozisyon Adı</th>
                <th class="center witdh10">Durum</th>
                <th class="center witdh10">Eklenme Tarihi</th>
                <th class="center witdh10">İşlem</th>
            </tr>
        </thead>
         <tbody id="item-list">
            @foreach (var item in Model)
            {
                <tr id="listItem_@item.HumanResourcePositionId"  class="handle">
                    <td class="center">
                        <img src="/Areas/Admin/Content/images/icons/tablesorter/arrow2.png" alt="move" border="0" class="handle sortimg" align="middle" />
                    </td>
                    <td>
                        <span id="spanitem_@item.HumanResourcePositionId">@item.HumanResourcePositionName</span>
                        <input type="text" id="textitem_@item.HumanResourcePositionId" value="" class="displaynone textwidth90"/>
                    </td>
                    <td class="center">
                        @if (item.Online == true)
                        {<img   id="img_online_@item.HumanResourcePositionId" src="/Areas/Admin/Content/images/icons/online.png" class="cursorpointer" title="Offline yap" onclick="SetOnlineStatus('/HumanResource/HumanResourcePositionEditStatus',@item.HumanResourcePositionId)" />}
                        else{<img id="img_online_@item.HumanResourcePositionId" src="/Areas/Admin/Content/images/icons/offline.png" class="cursorpointer" title="Online yap" onclick="SetOnlineStatus('/HumanResource/HumanResourcePositionEditStatus',@item.HumanResourcePositionId)" />}
                    </td>
                    <td class="center">@item.TimeCreated</td>
                    <td class="center">
                       <a href="/yonetim/insankaynaklari/pozisyonduzenle/@item.HumanResourcePositionId">
                        <img id="btn_update_@item.HumanResourcePositionId"  src="/Areas/Admin/Content/images/icons/16/edit.png"  title="Güncelle" class="cursorpointer" >
                       </a>
                        <img id="btn_save_@item.HumanResourcePositionId"  src="/Areas/Admin/Content/images/icons/16/save.png"  title="Kaydet" class="displaynone cursorpointer" onclick="UpdateRecord(@item.HumanResourcePositionId)">
                        <img id="btn_cancel_@item.HumanResourcePositionId"  src="/Areas/Admin/Content/images/icons/16/error.png"  title="İptal" class="displaynone cursorpointer" onclick="CancelRecord(@item.HumanResourcePositionId)">
                       <img id="DeleteImage_@item.HumanResourcePositionId"  src="/Areas/Admin/Content/images/icons/16/delete.png" class="cursorpointer"  title="Sil" onclick="DeleteRecord('/HumanResource/DeleteHumanResourcePosition',@item.HumanResourcePositionId)">
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>
 <br class="cl" />
<div id="info"></div>
</div>

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>

<script src="~/Areas/Admin/Content/scripts/myscripts/SetOnlineStatusRecord.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/DeleteRecordTable.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/SortOrder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/generalprocess.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/HumanResourcePosition/HumanResourcePositionlist.js"></script>

<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/tablesorter.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/jquery.tablesorter.pager.js"></script>

web/Areas/Admin/Views/HumanResource/Index.cshtml
@model DAL.Entities.HumanResource
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("hr_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>İNSAN KAYNAKLARI</h2>
    </div>  
  <section class="grid_12 form">
  
  @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage)
    @using(Html.BeginForm())
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>İnsan Kaynakları İçerik Yazısı</legend>
        <p>
            @Html.Label("Dil Seçimi")
            @Html.DropDownList("ddllanguage", (IEnumerable<SelectListItem>)ViewBag.LanguageList)
           
            
        </p>
        
              <br />
        <p>
            @Html.TextAreaFor(m => m.Content, new { id="txtcontent",@class="required"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <br />
      
        <p>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
    </fieldset>


    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
@*@System.Web.Optimization.Scripts.Render("~/admin/editor")*@
<script src="~/Areas/Admin/Content/CKEditor/ckeditor/ckeditor.js"></script>
<script src="~/Areas/Admin/Content/CKEditor/ckfinder/ckfinder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/CKEditorCreate.js"></script>


<script src="~/Areas/Admin/Content/scripts/pagescripts/instituional/hr.js"></script>

}

web/Areas/Admin/Views/HumanResource/hr_leftbar.cshtml
<aside>
<ul id="sidebar-nav"> 
<li><a href="#">İNSAN KAYNAKLARI</a>
<ul class="drop" style="display: block;">
     <li><a href="/yonetim/insankaynaklari"><img src="/Areas/Admin/Content/images/icons/16/page.png">İnsan Kaynakları</a></li>
     <li><a href="/yonetim/insankaynaklari/pozisyonlar"><img src="/Areas/Admin/Content/images/icons/16/page.png">Pozisyonlar</a></li>
     <li><a href="/yonetim/insankaynaklari/pozisyonekle"><img src="/Areas/Admin/Content/images/icons/16/page_add.png">Pozisyon Ekle</a></li>
</ul>
</li>
</ul>
<br /> <br /> 
      
</aside>