web/Areas/Admin/Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using web.Areas.Admin.Filters;
using BLL.LanguageBL;
using BLL.LinkBL;
using DAL.Entities;

namespace web.Areas.Admin.Controllers
{
     [AuthenticateUser]
    public class LinkController : Controller
    {
        //
        // GET: /Admin/Link/

        public ActionResult Index()
        {
            string sellang = FillLanguagesForList();

            var list = LinkManager.GetImportantLinksList(sellang);
            return View(list);
        }

        public ActionResult AddLink()
        {
            FillLanguagesList();
            return View();
        }


        [HttpPost]
        public ActionResult AddLink(ImportantLinks model)
        {
            FillLanguagesList();

            if (ModelState.IsValid)
            {
                ModelState.Clear();
                ViewBag.ProcessMessage = LinkManager.AddImportantLinks(model);
            }
            return View();
        }


        public ActionResult EditLink()
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if (RouteData.Values["id"] != null)
            {
                int nid = 0;
                bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                if (isnumber)
                {
                    ImportantLinks editrecord = LinkManager.GetImportantLinksById(nid);
                    return View(editrecord);
                }
                else
                    return View();
            }
            else
                return View();
            return View();
        }



        [HttpPost]
        public ActionResult EditLink(ImportantLinks model)
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;

            if (ModelState.IsValid)
            {
               
                if (RouteData.Values["id"] != null)
                {
                    int nid = 0;
                    bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                    if (isnumber)
                    {
                        model.LinkId = nid;
                        ViewBag.ProcessMessage = LinkManager.EditImportantLink(model);
                        return View(model);
                    }
                    else
                    {
                        ViewBag.ProcessMessage = false;
                        return View(model);
                    }
                }
                else return View();
            }
            else
                return View();

            return View();
        }






        public JsonResult EditStatus(int id)
        {
            string NowState;
            bool isupdate = LinkManager.UpdateStatus(id);
            return Json(isupdate);
        }


        public JsonResult DeleteRecord(int id)
        {
            bool isdelete = LinkManager.Delete(id);
            //if (isdelete)
            return Json(isdelete);
            //  else return false;
        }

        public JsonResult SortRecords(string list)
        {
            JsonList psl = (new JavaScriptSerializer()).Deserialize<JsonList>(list);
            string[] idsList = psl.list;
            bool issorted = LinkManager.SortRecords(idsList);
            return Json(issorted);


        }

        public class JsonList
        {
            public string[] list { get; set; }
        }
        string FillLanguagesForList()
        {
            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language", lang);
            ViewBag.LanguageList = list;
            return lang;
        }

        string FillLanguagesList()
        {
            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            return lang;
        }


      


    }
}

web/Areas/Admin/Views/Link/AddLink.cshtml
@model DAL.Entities.ImportantLinks
@{
    ViewBag.Title = "AddLink";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("link_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>ÖNEMLİ LİNK BİLGİLERİ</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using(Html.BeginForm("AddLink", "Link", FormMethod.Post, new { enctype = "multipart/form-data"}))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Link Ekle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.LinkName)
            @Html.TextBoxFor(m=>m.LinkName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.LinkName)
        </p>
        
      
        <p>
            @Html.LabelFor(m=>m.LinkUrl)
            @Html.TextBoxFor(m=>m.LinkUrl, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.LinkUrl)
        </p>
       
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/reference/addreference.js"></script>
}

web/Areas/Admin/Views/Link/EditLink.cshtml
@model DAL.Entities.ImportantLinks
@{
    ViewBag.Title = "EditLink";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("link_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>ÖNEMLİ LİNK BİLGİLERİ</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using(Html.BeginForm("EditLink", "Link", FormMethod.Post, new { enctype = "multipart/form-data"}))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Link Düzenle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.LinkName)
            @Html.TextBoxFor(m=>m.LinkName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.LinkName)
        </p>
        
      
        <p>
            @Html.LabelFor(m=>m.LinkUrl)
            @Html.TextBoxFor(m=>m.LinkUrl, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.LinkUrl)
        </p>
       
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/reference/addreference.js"></script>
}

web/Areas/Admin/Views/Link/Index.cshtml
@model IEnumerable<DAL.Entities.ImportantLinks>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("link_leftbar")


<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>ÖNEMLİ LİNK BİLGİLERİ</h2>
    </div>  
    <section class="grid_12 form">
    <div class="box-header" >
        <h1>Önemli Linkler Listesi&nbsp;&nbsp;|&nbsp;&nbsp;
             @Html.DropDownList("LanguageList")
        </h1>

    </div>
    <table id="tblcategory" class="table no-border tablesorter">
        <thead>
            <tr>
                <th class="width5">Sırala</th>
                <th class="width40">Link Adı</th>
                 <th class="width10 center">Durum</th>
                <th class="center witdh30">URL</th>
                <th class="center witdh10">İşlem</th>
            </tr>
        </thead>
         <tbody id="item-list">
            @foreach (var item in Model)
            {
                <tr id="listItem_@item.LinkId"  class="handle">
                    <td class="center">
                        <img src="/Areas/Admin/Content/images/icons/tablesorter/arrow2.png" alt="move" border="0" class="handle sortimg" align="middle" />
                    </td>
                    <td>
                        <span id="spanitem_@item.LinkId">@item.LinkName</span>
                        <input type="text" id="textitem_@item.LinkId" value="" class="displaynone textwidth90"/>
                    </td>
                    <td class="center">
                        @if (item.Online == true)
                        {<img   id="img_online_@item.LinkId" src="/Areas/Admin/Content/images/icons/online.png" class="cursorpointer" title="Offline yap" onclick="SetOnlineStatus('/Link/EditStatus',@item.LinkId)" />}
                        else{<img id="img_online_@item.LinkId" src="/Areas/Admin/Content/images/icons/offline.png" class="cursorpointer" title="Online yap" onclick="SetOnlineStatus('/Link/EditStatus',@item.LinkId)" />}
                    </td>
                    <td class="center">@item.LinkUrl</td>
                    <td class="center">
                       <a href="/yonetim/linkduzenle/@item.LinkId">
                        <img id="btn_update_@item.LinkId"  src="/Areas/Admin/Content/images/icons/16/edit.png"  title="Güncelle" class="cursorpointer" >
                       </a>
                        
                       <img id="DeleteImage_@item.LinkId"  src="/Areas/Admin/Content/images/icons/16/delete.png" class="cursorpointer"  title="Sil" onclick="DeleteRecord('/Link/DeleteRecord',@item.LinkId)">
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>
 <br class="cl" />
<div id="info"></div>
</div>

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/tablesorter.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/jquery.tablesorter.pager.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/TableSorterScript.js"></script>

<script src="~/Areas/Admin/Content/scripts/myscripts/SetOnlineStatusRecord.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/DeleteRecordTable.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/SortOrder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/generalprocess.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/links/linklist.js"></script>

web/Areas/Admin/Views/Link/link_leftbar.cshtml
<aside>
<ul id="sidebar-nav"> 
<li><a href="#">ÖNEMLİ LİNK İŞLEMLERİ</a>
<ul class="drop" style="display: block;">
     <li><a href="/yonetim/linkler"><img src="/Areas/Admin/Content/images/icons/16/page.png">Link Listesi</a></li>
    <li><a href="/yonetim/linkekle"><img src="/Areas/Admin/Content/images/icons/16/page_add.png">Link Ekle</a></li>
</ul>
</li>
</ul>
<br /> <br /> 
      
</aside>