web/Areas/Admin/Controllers/CertificateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using web.Areas.Admin.Filters;
using web.Areas.Admin.Helpers;
using BLL.LanguageBL;
using DAL.Entities;
using BLL.CertificateBL;

namespace web.Areas.Admin.Controllers
{
    [AuthenticateUser]
    public class CertificateController : Controller
    {
        //
        // GET: /Admin/Certificate/

        public ActionResult Index()
        {
            string sellang=FillLanguagesList();

            var referncelist = CertificateManager.GetCertificateList(sellang);
            return View(referncelist);
        }

        public ActionResult AddCertificate()
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
           
            return View();
        }

        [HttpPost]
        public ActionResult AddCertificate(Certificate newmodel, HttpPostedFileBase uploadfile)
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if (ModelState.IsValid)
            {
                if (uploadfile != null && uploadfile.ContentLength > 0)
                {
                    Random random = new Random();
                    int rand = random.Next(1000, 99999999);
                    new ImageHelper(240, 240).SaveThumbnail(uploadfile, "/Content/images/Certificate/", Utility.SetPagePlug(newmodel.CertificateName) + "_" + rand + Path.GetExtension(uploadfile.FileName));
                    newmodel.Logo = "/Content/images/Certificate/" + Utility.SetPagePlug(newmodel.CertificateName) + "_" + rand + Path.GetExtension(uploadfile.FileName);
                }
                else
                {
                    newmodel.Logo = "/Content/images/front/noimage.jpeg";
                }
                newmodel.SortOrder = 9999;
                newmodel.TimeCreated = DateTime.Now;
                ViewBag.ProcessMessage = CertificateManager.AddCertificate(newmodel);
                ModelState.Clear();
                // Response.Redirect("/yonetim/haberduzenle/" + newsmodel.NewsId);
                return View();
            }
            else
                return View();
        }

        public ActionResult EditCertificate()
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if (RouteData.Values["id"] != null)
            {
                int nid = 0;
                bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                if (isnumber)
                {
                    Certificate editCertificate = CertificateManager.GetCertificateById(nid);
                    return View(editCertificate);
                }
                else
                    return View();
            }
            else
                return View();
        }

        [HttpPost]
        public ActionResult EditCertificate(Certificate Certificatemodel, HttpPostedFileBase uploadfile)
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;

            if (ModelState.IsValid)
            {
                if (uploadfile != null && uploadfile.ContentLength > 0)
                {
                    Random random = new Random();
                    int rand = random.Next(1000, 99999999);
                    new ImageHelper(240, 240).SaveThumbnail(uploadfile, "/Content/images/Certificate/", Utility.SetPagePlug(Certificatemodel.CertificateName) + "_" + rand + Path.GetExtension(uploadfile.FileName));
                    Certificatemodel.Logo = "/Content/images/Certificate/" + Utility.SetPagePlug(Certificatemodel.CertificateName) + "_" + rand + Path.GetExtension(uploadfile.FileName);
                }


                if (RouteData.Values["id"] != null)
                {
                    int nid = 0;
                    bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                    if (isnumber)
                    {
                        Certificatemodel.CertificateId = nid;
                        ViewBag.ProcessMessage = CertificateManager.EditCertificate(Certificatemodel);
                        return View(Certificatemodel);
                    }
                    else
                    {
                        ViewBag.ProcessMessage = false;
                        return View(Certificatemodel);
                    }
                }
                else  return View();
            }
            else
                return View();

            return View();
        }


        public JsonResult CertificateEditStatus(int id)
        {
            string NowState;
            bool isupdate = CertificateManager.UpdateStatus(id);
            return Json(isupdate);
        }

        
        public JsonResult DeleteCertificate(int id)
        {
            bool isdelete = CertificateManager.Delete(id);
            //if (isdelete)
            return Json(isdelete);
          //  else return false;
        }

        string FillLanguagesList()
        {
            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language", lang);
            ViewBag.LanguageList = list;
            return lang;
        }

        public JsonResult SortRecords(string list)
        {
            JsonList psl = (new JavaScriptSerializer()).Deserialize<JsonList>(list);
            string[] idsList = psl.list;
            bool issorted = CertificateManager.SortRecords(idsList);
            return Json(issorted);


        }

        public class JsonList
        {
            public string[] list { get; set; }
        }
       

    }
}

web/Areas/Admin/Views/Certificate/AddCertificate.cshtml
@model DAL.Entities.Certificate
@{
    ViewBag.Title = "AddCertificate";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("Certificate_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>SERTİFİKA BİLGİLERİ</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using (Html.BeginForm("AddCertificate", "Certificate", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Çözüm Ortağı Ekle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.CertificateName)
            @Html.TextBoxFor(m=>m.CertificateName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.CertificateName)
        </p>
        
        <p>
            <label for="txtname">Logo</label>
            
            <input type="file" name="uploadfile" id="uploadfile" />
        </p>
        <p>
            @Html.LabelFor(m=>m.Link)
            @Html.TextBoxFor(m=>m.Link, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.Link)
        </p>
        <p>
            @Html.LabelFor(m=>m.Content)
            @Html.TextAreaFor(m=>m.Content, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/Certificate/addCertificate.js"></script>
}

web/Areas/Admin/Views/Certificate/Certificate_leftbar.cshtml
<aside>
<ul id="sidebar-nav"> 
<li><a href="#">SERTİFİKA İŞLEMLERİ</a>
<ul class="drop" style="display: block;">
    <li><a href="/yonetim/sertifikalar"><img src="/Areas/Admin/Content/images/icons/16/page.png">Sertifika Listesi</a></li>
     <li><a href="/yonetim/sertifikaekle"><img src="/Areas/Admin/Content/images/icons/16/page_add.png">Yeni Sertifika</a></li>
    
</ul>
</li>
</ul>
<br /> <br /> 
      
</aside>

web/Areas/Admin/Views/Certificate/EditCertificate.cshtml
@model DAL.Entities.Certificate
@{
    ViewBag.Title = "EditCertificate";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("Certificate_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>SERTIFIKA BILGILERI</h2>
    </div> 
    
<section class="grid_12 form">
    @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage) 
    @using (Html.BeginForm("EditCertificate", "Certificate", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Sertifika Duzenle</legend>
        <p>
            @Html.LabelFor(m=>m.Language)
            @Html.DropDownListFor(m=>m.Language,(IEnumerable<SelectListItem>)ViewBag.LanguageList,"Dil Seçiniz...")
            @Html.ValidationMessageFor(m=>m.Language)
           
        </p>

        <p>
            @Html.LabelFor(m=>m.CertificateName)
            @Html.TextBoxFor(m=>m.CertificateName, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m => m.CertificateName)
        </p>
        
        <p>
            <label for="txtname">Logo</label>
            
            <input type="file" name="uploadfile" id="uploadfile" />
        </p>
        <p>
            @Html.LabelFor(m=>m.Link)
            @Html.TextBoxFor(m=>m.Link, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.Link)
        </p>
        <p>
            @Html.LabelFor(m=>m.Content)
            @Html.TextAreaFor(m=>m.Content, new { @class="textwidth50"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <p>
            <label></label>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
       
    </fieldset>
    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/Certificate/addCertificate.js"></script>
}

web/Areas/Admin/Views/Certificate/Index.cshtml
@model IEnumerable<DAL.Entities.Certificate>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("Certificate_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>SERTİFİKA BİLGİLERİ</h2>
    </div>  
    <section class="grid_12 form">
    <div class="box-header" >
        <h1>Sertifika Listesi&nbsp;&nbsp;|&nbsp;&nbsp;
             @Html.DropDownList("LanguageList")
        </h1>

    </div>
    <table id="tblcategory" class="table no-border tablesorter">
        <thead>
            <tr>
                 <th class="width5">Sırala</th>
                <th class="width50">Sertifika Adı</th>
                <th class="center witdh10">Durum</th>
                <th class="center witdh10">Eklenme Tarihi</th>
                <th class="center witdh10">İşlem</th>
            </tr>
        </thead>
         <tbody id="item-list">
            @foreach (var item in Model)
            {
                <tr id="listItem_@item.CertificateId"  class="handle">
                    <td class="center">
                        <img src="/Areas/Admin/Content/images/icons/tablesorter/arrow2.png" alt="move" border="0" class="handle sortimg" align="middle" />
                    </td>
                    <td>
                        <span id="spanitem_@item.CertificateId">@item.CertificateName</span>
                        <input type="text" id="textitem_@item.CertificateId" value="" class="displaynone textwidth90"/>
                    </td>
                    <td class="center">
                        @if (item.Online == true)
                        {<img   id="img_online_@item.CertificateId" src="/Areas/Admin/Content/images/icons/online.png" class="cursorpointer" title="Offline yap" onclick="SetOnlineStatus('/Certificate/CertificateEditStatus',@item.CertificateId)" />}
                        else{<img id="img_online_@item.CertificateId" src="/Areas/Admin/Content/images/icons/offline.png" class="cursorpointer" title="Online yap" onclick="SetOnlineStatus('/Certificate/CertificateEditStatus',@item.CertificateId)" />}
                    </td>
                    <td class="center">@item.TimeCreated</td>
                    <td class="center">
                       <a href="/yonetim/sertifikaduzenle/@item.CertificateId">
                        <img id="btn_update_@item.CertificateId"  src="/Areas/Admin/Content/images/icons/16/edit.png"  title="Güncelle" class="cursorpointer" >
                       </a>
                        <img id="btn_save_@item.CertificateId"  src="/Areas/Admin/Content/images/icons/16/save.png"  title="Kaydet" class="displaynone cursorpointer" onclick="UpdateRecord(@item.CertificateId)">
                        <img id="btn_cancel_@item.CertificateId"  src="/Areas/Admin/Content/images/icons/16/error.png"  title="İptal" class="displaynone cursorpointer" onclick="CancelRecord(@item.CertificateId)">
                       <img id="DeleteImage_@item.CertificateId"  src="/Areas/Admin/Content/images/icons/16/delete.png" class="cursorpointer"  title="Sil" onclick="DeleteRecord('/Certificate/DeleteCertificate',@item.CertificateId)">
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>
 <br class="cl" />
<div id="info"></div>
</div>

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>

<script src="~/Areas/Admin/Content/scripts/myscripts/SetOnlineStatusRecord.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/DeleteRecordTable.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/SortOrder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/generalprocess.js"></script>
<script src="~/Areas/Admin/Content/scripts/pagescripts/Certificate/Certificatelist.js"></script>

<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/tablesorter.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/jquery.tablesorter.pager.js"></script>