web/Areas/Admin/Controllers/SectorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using web.Areas.Admin.Helpers;
using BLL.LanguageBL;
using BLL.SectorBL;
using DAL.Entities;
using web.Areas.Admin.Filters;
using BLL.SectorGroupBL;

namespace web.Areas.Admin.Controllers
{
      [AuthenticateUser]
    public class SectorController : Controller
    {
        //
        // GET: /Admin/Sector/

        public ActionResult Index()
        {
            string id = FillLanguagesList();
            int groupid = Convert.ToInt32(id);

            var list = SectorManager.GetSectorList(groupid);
            return View(list);
        }

        public ActionResult OurSectors()
        {
            FillLanguagesList();

            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var Sectorpage = SectorManager.GetOurSectors(lang);
            return View(Sectorpage);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult OurSectors(OurSectors record)
        {
            FillLanguagesList();
            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();
            record.Language = lang;
            ViewBag.ProcessMessage = SectorManager.EditOurSectors(record);
            return View();
        }

        public ActionResult AddSector()
        {
            FillLanguagesList();
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddSector(Sector newmodel, HttpPostedFileBase uploadfile, HttpPostedFileBase uploadimage)
        {
            FillLanguagesList();

            if (ModelState.IsValid)
            {
               
                newmodel.PageSlug = Utility.SetPagePlug(newmodel.Name);
                newmodel.TimeCreated = DateTime.Now;
                ViewBag.ProcessMessage = SectorManager.AddSector(newmodel);
                ModelState.Clear();

                return View();
            }
            else
                return View();
        }


        public ActionResult EditSector()
        {
            FillLanguagesList();

            if (RouteData.Values["id"] != null)
            {
                int nid = 0;
                bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                if (isnumber)
                {
                    Sector editrecord = SectorManager.GetSectorById(nid);
                    return View(editrecord);
                }
                else
                    return View();
            }
            else
                return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditSector(Sector newmodel, HttpPostedFileBase uploadfile, HttpPostedFileBase uploadimage)
        {
            FillLanguagesList();

            if (ModelState.IsValid)
            {
               
                newmodel.PageSlug = Utility.SetPagePlug(newmodel.Name);

                if (RouteData.Values["id"] != null)
                {
                    int nid = 0;
                    bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                    if (isnumber)
                    {
                        newmodel.SectorId = nid;
                        ViewBag.ProcessMessage = SectorManager.EditSector(newmodel);
                        return View(newmodel);
                    }
                    else
                    {
                        ViewBag.ProcessMessage = false;
                        return View(newmodel);
                    }
                }
                else return View();
            }
            else
                return View();
        }

        string FillLanguagesList()
        {
            string lang = "";
            string id = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language", lang);
            ViewBag.LanguageList = list;

            var groups = SectorGroupManager.GetSectorGroupList(lang);

            if (RouteData.Values["id"] == null)
            {
                if (groups != null && groups.Count != 0)
                    id = groups.First().SectorGroupId.ToString();
                else id = "0";
            }
            else id = RouteData.Values["id"].ToString();


            var grouplist = new SelectList(groups, "SectorGroupId", "GroupName", id);
            ViewBag.GroupList = grouplist;

            return id;
        }


        public JsonResult EditStatus(int id)
        {
            bool isupdate = SectorManager.UpdateStatus(id);
            return Json(isupdate);
        }


        public JsonResult Delete(int id)
        {
            bool isdelete = SectorManager.Delete(id);
            //if (isdelete)
            return Json(isdelete);
            //  else return false;
        }

        [HttpPost]
        public ActionResult LoadGroup(string lang)
        {
            var grouplst = SectorGroupManager.GetSectorGroupList(lang);
            JsonResult result = Json(new SelectList(grouplst, "SectorGroupId", "GroupName"));
            return result;
        }

        public JsonResult SortRecords(string list)
        {
            JsonList psl = (new JavaScriptSerializer()).Deserialize<JsonList>(list);
            string[] idsList = psl.list;
            bool issorted = SectorManager.SortRecords(idsList);
            return Json(issorted);
        }
        public class JsonList
        {
            public string[] list { get; set; }
        }
       
    }
}

web/Areas/Admin/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using web.Areas.Admin.Helpers;
using BLL.LanguageBL;
using BLL.ServiceBL;
using DAL.Entities;
using web.Areas.Admin.Filters;
using BLL.ServiceGroupBL;

namespace web.Areas.Admin.Controllers
{
      [AuthenticateUser]
    public class ServiceController : Controller
    {
        //
        // GET: /Admin/Service/

        public ActionResult Index()
        {
            string id = FillLanguagesList();
            int groupid = Convert.ToInt32(id);

            var list = ServiceManager.GetServiceList(groupid);
            return View(list);
        }

        public ActionResult OurServices()
        {
            FillLanguagesList();

            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var servicepage = ServiceManager.GetOurServices(lang);
            return View(servicepage);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult OurServices(OurServices record)
        {
            FillLanguagesList();
            string lang = "";
            string id = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();
            record.Language = lang;
            ViewBag.ProcessMessage = ServiceManager.EditOurServices(record);
            return View();
        }

        public ActionResult AddService()
        {
            FillLanguagesList();
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddService(Service newmodel, HttpPostedFileBase uploadfile, HttpPostedFileBase uploadimage)
        {
            FillLanguagesList();

            if (ModelState.IsValid)
            {
               
                newmodel.PageSlug = Utility.SetPagePlug(newmodel.Name);
                newmodel.TimeCreated = DateTime.Now;
                ViewBag.ProcessMessage = ServiceManager.AddService(newmodel);
                ModelState.Clear();

                return View();
            }
            else
                return View();
        }


        public ActionResult EditService()
        {
            FillLanguagesList();

            if (RouteData.Values["id"] != null)
            {
                int nid = 0;
                bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                if (isnumber)
                {
                    Service editrecord = ServiceManager.GetServiceById(nid);
                    return View(editrecord);
                }
                else
                    return View();
            }
            else
                return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditService(Service newmodel, HttpPostedFileBase uploadfile, HttpPostedFileBase uploadimage)
        {
            FillLanguagesList();

            if (ModelState.IsValid)
            {
               
                newmodel.PageSlug = Utility.SetPagePlug(newmodel.Name);

                if (RouteData.Values["id"] != null)
                {
                    int nid = 0;
                    bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                    if (isnumber)
                    {
                        newmodel.ServiceId = nid;
                        ViewBag.ProcessMessage = ServiceManager.EditService(newmodel);
                        return View(newmodel);
                    }
                    else
                    {
                        ViewBag.ProcessMessage = false;
                        return View(newmodel);
                    }
                }
                else return View();
            }
            else
                return View();
        }

        string FillLanguagesList()
        {
            string lang = "";
            string id = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language", lang);
            ViewBag.LanguageList = list;

            var groups = ServiceGroupManager.GetServiceGroupList(lang);

            if (RouteData.Values["id"] == null)
            {
                if (groups != null && groups.Count != 0)
                    id = groups.First().ServiceGroupId.ToString();
                else id = "0";
            }
            else id = RouteData.Values["id"].ToString();


            var grouplist = new SelectList(groups, "ServiceGroupId", "GroupName", id);
            ViewBag.GroupList = grouplist;

            return id;
        }


        public JsonResult EditStatus(int id)
        {
            string NowState;
            bool isupdate = ServiceManager.UpdateStatus(id);
            return Json(isupdate);
        }


        public JsonResult Delete(int id)
        {
            bool isdelete = ServiceManager.Delete(id);
            //if (isdelete)
            return Json(isdelete);
            //  else return false;
        }

        [HttpPost]
        public ActionResult LoadGroup(string lang)
        {
            var grouplst = ServiceGroupManager.GetServiceGroupList(lang);
            JsonResult result = Json(new SelectList(grouplst, "ServiceGroupId", "GroupName"));
            return result;
        }

        public JsonResult SortRecords(string list)
        {
            JsonList psl = (new JavaScriptSerializer()).Deserialize<JsonList>(list);
            string[] idsList = psl.list;
            bool issorted = ServiceManager.SortRecords(idsList);
            return Json(issorted);
        }
        public class JsonList
        {
            public string[] list { get; set; }
        }
       
    }
}

web/Controllers/FHomeController.cs
using System.Linq;
using System.Web.Mvc;
using web.Models;
using BLL.NewsBL;
using BLL.ReferenceBL;
using BLL.Project;
using BLL.DocumentsBL;
using BLL.PhotoBL;
using BLL.SectorGroupBL;
using BLL.ProductBL;
namespace web.Controllers
{
    public class FHomeController : Controller
    {
        string lang = System.Threading.Thread.CurrentThread.CurrentUICulture.ToString();
        
        public ActionResult Index()
        {
            var news = NewsManager.GetNewsListForFront(lang).Take(4);
            var references = ReferenceManager.GetReferenceListForFront(lang);
            var docgroup = DocumentManager.GetDocumentGroupListForFront(lang).First();
            var docs = DocumentManager.GetDocumentListForFront(docgroup.DocumentGroupId).Take(5);
            var projects = ProjectManager.GetProjectListForFront(lang).Take(4);
            var photos = PhotoManager.GetListForFront(lang, 0);
            var sectors = SectorGroupManager.GetSectorGroupListForFront(lang);
            var prods = ProductManager.GetProductListAllForFront(lang);
            ViewBag.docgroupSlug = docgroup.PageSlug;
            ViewBag.docgroupid = docgroup.DocumentGroupId;
            ViewBag.docgroup = docgroup.GroupName;
            HomePageWrapperModel modelbind = new HomePageWrapperModel(prods, sectors, news, references, projects, docs, photos);
            return View(modelbind);
        }

        public ActionResult ChangeCulture(string lang,string returnUrl)
        {
            Session["culture"] = lang;
            if(lang=="en")
                return Redirect("/en/homepage");
            return Redirect("/tr/anasayfa");
        }
    }
}

web/Controllers/FSearchController.cs
using BLL.SearchBL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web.Controllers
{
    public class FSearchController : Controller
    {
        //
        // GET: /Shared/

        public ActionResult _search()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string SearchText)
        {
            var result = SearchManager.Search(SearchText);
            return View(result);
        }
    }
}

web/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Page Not Found";
    Layout = "~/Views/Shared/frontlayout.cshtml";
}
<div class="main_content mainpage pageheight" style="">
    <div class="wrapper mainpage grid_12">
        <div class="content_page page">
            <h3>@NotFoundRess.NotFoundStrings.notfound</h3>
            <hr class="wide" />
            <div style="margin: 0 auto; width: 450px;">
                <h1 style="text-align: center; padding-bottom:20px;">@NotFoundRess.NotFoundStrings.notfoundcontent</h1>
                <img src="http://en.balticmedia.com/bm/images/404-Page-Not-Found.png" />
            </div>
        </div>
    </div>
</div>

web/Views/Shared/_Sectors.cshtml
@model web.Models.SectorSubWrapperModel

@foreach (var sub in Model.sectors)
{
    <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_sectors/@Model.sectorgroup.PageSlug/@sub.PageSlug/@sub.SectorId">@sub.Name</a></li>
}

web/Views/Shared/_emptyOfferList.cshtml
<div style="text-align: center; padding: 5px;">
    <img alt="alert, exclamation, message, warning icon" class="tiled-icon" style="margin-top: 20px; width: 128px; height: 128px;"
        src="/Content/Images/Front/alert.png">
</div>
<div style="text-align: center; padding: 5px;">
    <p style="font-size: 12px; color: #00a1d0"><b>@OfferRess.OffersStrings.emptylist</b></p>
    <p style="font-size: 12px;">@OfferRess.OffersStrings.addproductmessage</p>
</div>

web/Views/Shared/_main2Left.cshtml
<div class="main2Left">
    <div class="urunler leftMenu">
        <h2 class="sectionTitle"><span>@SharedRess.SharedStrings.aboutus</span></h2>
        <ul>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_aboutus">@SharedRess.SharedStrings.aboutus</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_solutionpartners">@SharedRess.SharedStrings.solutionpartners</a></li>
       @* <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_certificates">@SharedRess.SharedStrings.certificates</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_equipments">@SharedRess.SharedStrings.equipments</a></li>*@
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_humanresources">@SharedRess.SharedStrings.humanresources</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_references">@SharedRess.SharedStrings.references</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_contactdetails">@SharedRess.SharedStrings.contact</a></li>
        </ul>
    </div>
</div>

web/Views/Shared/_search.cshtml
<style type="text/css">
    #srcbtn{ float:left; cursor:pointer; border:none; padding:0px; width:29px; height:29px; position:relative; z-index:9999; }
    .search input[type="text"] { float:left; background-image:none; margin-right:0px; width:146px; }
    .search input[type="submit"] { float:left; margin-left:0px; margin-right:18px; background: #fff url(/img/search.png) 3px center no-repeat;}
</style>
@using (Html.BeginForm("Index", "FSearch"))
{
    
    <input name="SearchText" type="text" onblur="this.value=(this.value=='') ? '@SharedRess.SharedStrings.searchinsite' : this.value;" onfocus="this.value=(this.value=='@SharedRess.SharedStrings.searchinsite') ? '' : this.value;" value="@SharedRess.SharedStrings.searchinsite" alt="@SharedRess.SharedStrings.searchinsite" class="text_input">
    <input id="srcbtn" name="submit" type="submit" value="">
}

web/Views/Shared/_sentOfferList.cshtml
<div style="text-align: center; padding: 5px;">
    <img alt="success icon" class="tiled-icon" style="margin-top: 20px; width: 128px; height: 128px;"
        src="/Content/Images/Front/check.png">
</div>
<div style="text-align: center; padding: 5px;">
    <p style="font-size: 12px; color: #00a1d0"><b>@OfferRess.OffersStrings.offerdeliveredmessage</b></p>
    <p style="font-size: 12px;">@OfferRess.OffersStrings.offernotifymessage</p>
</div>

web/Views/Shared/_services.cshtml
@model web.Models.ServiceSubWrapperModel

@foreach (var sub in Model.services)
{
    <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_services/@Model.servicegroup.PageSlug/@sub.PageSlug/@sub.ServiceId">@sub.Name</a></li>
}

web/Views/Shared/_subproductgroups.cshtml
@model web.Models.ProductSubWrapperModel

@foreach (var sub in Model.productsubgroups)
{
    <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_products/@Model.productgroup.PageSlug/@sub.PageSlug/@sub.ProductSubGroupId">@sub.GroupName</a></li>
}

web/Views/Shared/frontlayout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width" />
<title>Kontrolmatik | Anasayfa</title>
<link href="~/css/style.css" rel="stylesheet" />
<script src="~/js/jquery-1.8.3.min.js" type="text/javascript"></script>
<script src="~/Content/Scripts/modernizr-2.0.4.min.js" type="text/javascript"></script>
</head>
<body>
<div class="bg">
  <div class="wrapper2">
    <div class="header2"> <a href="/" class="logo2"><img src="/img/logo.png" border="0" /></a>
      <div class="search">
         @{ Html.RenderAction("_search", "FSearch"); }
      </div>
      <ul class="topMenu">
        <li>@Html.ActionLink("TR", "ChangeCulture", "FHome", new { lang = "tr", returnUrl = this.Request.RawUrl }, null)</li>
        <li>@Html.ActionLink("EN", "ChangeCulture", "FHome", new { lang = "en", returnUrl = this.Request.RawUrl }, null)</li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_contactdetails" class="last">@SharedRess.SharedStrings.contact.ToUpper()</a></li>
      </ul>
      <ul class="firstMenu">
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_aboutus">@SharedRess.SharedStrings.aboutus</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_services">@SharedRess.SharedStrings.services</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_sectors">@SharedRess.SharedStrings.sectors</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_products">@SharedRess.SharedStrings.products</a></li>
        <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_references">@SharedRess.SharedStrings.references</a></li>
      </ul>
    </div>
    <div class="main2">
        @RenderBody()
    </div>
    <div class="footer2">
      <div class="footerLeft">
        <ul>
          <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_aboutus">@SharedRess.SharedStrings.aboutus</a></li>
          <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_services">@SharedRess.SharedStrings.services</a></li>
          <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_sectors">@SharedRess.SharedStrings.sectors</a></li>
          <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_products">@SharedRess.SharedStrings.products</a></li>
          <li><a href="/@SharedRess.SharedStrings.menu_culture/@SharedRess.SharedStrings.menu_references">@SharedRess.SharedStrings.references</a></li>
        </ul>
        <p><span>@SharedRess.SharedStrings.address:</span> Tekstilkent Koza Plaza A Blok No:11 Esenler/İSTANBUL<br/>
          <span>@SharedRess.SharedStrings.phone:</span> +90 212 659 24 41 - 438 24 41<br/>
          <span>@SharedRess.SharedStrings.fax:</span> +90 212 659 24 81<br/>
          <span>@SharedRess.SharedStrings.email:</span> info@kontrolmatik.com</p>
      </div>
      <div class="footerRight">
        <p><img src="/img/logoFooter.png" style="margin-bottom: -4px;margin-right: 2px;"/> Copyright 2013</p>
        <p>Designed and Development <a href="http://www.wortec.net">WORTEC</a></p>
      </div>
    </div>
  </div>
</div>
</body>
</html>